num1= input("enter a number: ")
num2= input("enter another number: ")
add=int(num1)+int(num2)
sub=int(num1)-int(num2)
mul=int(num1)*int(num2)
div=int(num1)/int(num2)
mod=int(num1)%int(num2)
print(add)
print(sub)
print(mul)
print(div)
print(mod)