name=input("enter your name: ")
age=int(input("enter your age: "))
height=float(input("enter your height: "))
print("Name:",name)
print("Datatype of Name:",type(name))
print("Age:",age)
print("Datatype of Age:",type(age))
print("Height:",height)
print("Datatype of Height:",type(height))